@startuml sub_state_machine_register

title Register\n   

skinparam {
    TitleFontSize 20
    ClassFontSize 14
    DefaultTextAlignment left
    LegendFontSize 12
    LegendBackgroundColor LightGrey
    LegendBorderColor White
}

state Alice{
[*]-->RegisteredState_A:User: //Registering transaction state//

[*]-->ConcludedState_A:User: //Calling ConcludeFinal//
[*]-->ProgressionState_A:User: //Not responding//
RegisteredState_A-->RegisteredState_A:User:// Mak refute//
RegisteredState_A-->ConcludedState_A:// Timeout//\n User:// Making state conclusion//
ProgressionState_A-->ConcludedState_A:// Timeout//\n Nodemanager: //Make the conclusion//
ConcludedState_A-->ReadyToSettle_A:NodeManager:// Amount is finalised//
ReadyToSettle_A-->[*]
}

state Bob{
[*]-->RegisteredState:User: //Registering transaction state//
[*]-->ConcludedState:User: //Calling ConcludeFinal//
[*]-->ProgressionState:User: //Not responding//
RegisteredState-->RegisteredState:User:// Make refute//
RegisteredState-->ConcludedState:// Timeout//\n User:// Making state conclusion//
ProgressionState-->ConcludedState:// Timeout//\n Nodemanager: //Make the conclusion//
ConcludedState-->ReadyToSettle:NodeManager:// Amount is finalised//
ReadyToSettle-->[*]

}

RegisteredState-->RegisteredState_A:User :// Make refute//


@enduml