@startuml sub_state_machine_transaction

title Transaction\n

skinparam {
    TitleFontSize 20
    ClassFontSize 14
    DefaultTextAlignment left
    LegendFontSize 12
    LegendBackgroundColor LightGrey
    LegendBorderColor White
}

state Alice{
[*]-->ProposeNewState:Channel: //Open for transaction//
[*]-->HalfSigned:Channel: //Open for transaction//
ProposeNewState-->HalfSigned:User: //PartiallySigned//
ProposeNewState-->HalfSignedWithFinalState:User://PartiallySigned and set final state//
HalfSigned-->FullySigned:User: //Accept new state//
HalfSignedWithFinalState-->FullySignedWithFinalState:User://Accept new state//
HalfSigned-->RejectedState:User: //Reject new state//
HalfSignedWithFinalState-->RejectedState:User: //Reject new state//
HalfSignedWithFinalState-->[*]:User://Not respoding//
FullySignedWithFinalState-->[*]:User://Initialize close//
RejectedState-->ProposeNewState:User: //Make another transaction//
FullySigned-->ProposeNewState:User: //Make another transaction//
RejectedState-->[*]:User: //Initialize close// 
ProposeNewState-->[*]://Timeout//

HalfSigned-->[*]:User://Not respoding//
FullySigned-->[*]:User: //Initialize close//
}

state Bob{
[*]-->ProposeNewState_b:Channel: //Open for transaction//
[*]-->HalfSigned_b:Channel: //Open for transaction//
ProposeNewState_b-->HalfSigned_b:User: //PartiallySigned//
ProposeNewState_b-->HalfSignedWithFinalState_b:User://PartiallySigned and set final state//
HalfSigned_b-->FullySigned_b:User: //Accept new state//
HalfSignedWithFinalState_b-->FullySignedWithFinalState_b:User://Accept new state//
HalfSigned_b-->RejectedState_b:User: //Reject new state//
HalfSignedWithFinalState_b-->RejectedState_b:User: //Reject new state//
HalfSignedWithFinalState_b-->[*]:User://Not respoding//
FullySignedWithFinalState_b-->[*]:User://Initialize close// 
RejectedState_b-->ProposeNewState_b:User: //Make another transaction//
FullySigned_b-->ProposeNewState_b:User: //Make another transaction//
RejectedState_b-->[*]:User: //Initialize close// 
ProposeNewState_b-->[*]://Timeout//

HalfSigned_b-->[*]:User: //initialize close //
FullySigned_b-->[*]:User: //Initialize close //

}

HalfSignedWithFinalState_b-->FullySignedWithFinalState
HalfSignedWithFinalState_b-->RejectedState

@enduml